### ISSUE TITLE
failed building service 'web'

### ISSUE THREAD

**Issue by angandin** [Azure-Samples/azure-search-openai-demo-csharp#106]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Open repo in Codespaces
2. open bash terminal
3. execute azd auth login
4. execute azd up

### Any log messages given by the failure
<img width="733" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/40630711/8901ec5d-081b-40c1-8b1c-5b3a80f90667">

### Expected/desired behavior
Deploy the solution into specified azure subscription

### OS and Version?
Opened the repo with provided Codespaces

**Comment by luisquintanilla** [comment]
Hi @angandin,

Sorry to hear you ran into issues.

@jongio do you know why this might be happening?

**Comment by erezbatish-ms** [comment]
I'm experiencing the same issue, I'm running it locally from VS Code.

**Comment by luisquintanilla** [comment]
@angandin @erezbatish-ms I believe the issue may be because Docker isn't running. Can you make sure that it's running?

**Codespaces**

![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/46974588/e36944e1-3240-4532-8c33-49bdcbd141df)

If there is a number displayed on screen for the process ID then it means Docker is running.

**Local**

If you're on Linux, the same command should work. On Windows, just make sure to open Docker Desktop and start the daemon that way.

**Comment by erezbatish-ms** [comment]
Hi Luis

Docker is running on my laptop (I’m using Mac).
This is the error I get:

ERROR: failed building service 'web': failing invoking action 'build', building container: web at ../: building image: exit code: 1, stdout: , stderr: Dockerfile:14
--------------------
  12 |     COPY ["frontend/", "frontend/"]
  13 |     COPY ["shared/", "shared/"]
  14 | >>> RUN dotnet restore "backend/MinimalApi.csproj"
  15 |     COPY . .
  16 |     WORKDIR "/src/backend"
--------------------
ERROR: failed to solve: process "/bin/sh -c dotnet restore \"backend/MinimalApi.csproj\"" did not complete successfully: exit code: 137

The build process is running for like 30 min until it is exit with this error, in docker monitor I can see the memory is increasing until it reached the limit (hench exit code 137).
My docker is set for 8GB of memory.

Thanks
Erez

From: Luis Quintanilla ***@***.***>
Date: Wednesday, 7 June 2023 at 16:54
To: Azure-Samples/azure-search-openai-demo-csharp ***@***.***>
Cc: Erez Batish ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure-Samples/azure-search-openai-demo-csharp] failed building service 'web' (Issue #106)

@angandin<https://github.com/angandin> @erezbatish-ms<https://github.com/erezbatish-ms> I believe the issue may be because Docker isn't running. Can you make sure that it's running?

Codespaces

[Image removed by sender. image]<https://user-images.githubusercontent.com/46974588/244088466-e36944e1-3240-4532-8c33-49bdcbd141df.png>

If there is a number displayed on screen for the process ID then it means Docker is running.

Local

If you're on Linux, the same command should work. On Windows, just make sure to open Docker Desktop and start the daemon that way.

**Comment by luisquintanilla** [comment]
@erezbatish-ms thanks for that info. Looks like your issue is different from the original issue. Could you try running the sample in Codespaces? I don't have a Mac so I can't repro on that environment.

**Comment by erezbatish-ms** [comment]
The issue is that I’m using corp subscription which is not allowing to be authorized from a non-managed device, so I can’t run It in Codespaces.
I can try to run Codespaces from VS Code and see if it will allow me to auth to my subscription.




From: Luis Quintanilla ***@***.***>
Date: Wednesday, 7 June 2023 at 17:05
To: Azure-Samples/azure-search-openai-demo-csharp ***@***.***>
Cc: Erez Batish ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure-Samples/azure-search-openai-demo-csharp] failed building service 'web' (Issue #106)

@erezbatish-ms<https://github.com/erezbatish-ms> thanks for that info. Looks like your issue is different from the original issue. Could you try running the sample in Codespaces? I don't have a Mac so I can't repro on that environment.

**Comment by lynnaloo** [comment]
I can into the same issue on Mac as well. I'll update this if I can find a resolution to the issue.

**Comment by lynnaloo** [comment]
This pull request resolved this error for me: https://github.com/Azure-Samples/azure-search-openai-demo-csharp/pull/111.

**Comment by charris-msft** [comment]
@luisquintanilla  - I'm still seeing the failure if Docker Desktop is not running.

I'd suggest mentioning that requirement before each instruction to run `azd up`.

**Comment by luisquintanilla** [comment]
> @luisquintanilla - I'm still seeing the failure if Docker Desktop is not running.
> 
> I'd suggest mentioning that requirement before each instruction to run `azd up`.

Good suggestion. It's in our prereqs but having it as a reminder in the `azd` instructions would help.

**Comment by luisquintanilla** [comment]
Marking item as complete.
