### ISSUE TITLE
text-davinci-003 is not supported anymore for new deployements

### ISSUE THREAD

**Issue by tvriesde** [Azure-Samples/azure-search-openai-demo-csharp#115]
Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. 
DeploymentModelNotSupported: Creating account deployment is not supported by the model 'text-davinci-003'. This is usually because there are better models available for the similar functionality.

**Comment by rakshith-sb2** [comment]
even im facing the same issue

**Comment by levu74** [comment]
I'm facing the same issue. I have to switch to gpt-35-turbo instead

**Comment by rbakhishli1** [comment]
Hi all, did anyone solve this issue? which fields do we need to change to gpt-35-turbo?

**Comment by rakshith-sb2** [comment]
> 

were to change the version

**Comment by rakshith-sb2** [comment]
> > > 
> > 
> > 
> > were to change the version
> 
> infra>main.bicep
thanks @rbakhishli1 
yes it worked for me when I changed   text-davinci-003 to gpt-35-turbo. and change the version from version: '1' to version: '0301'

**Comment by rakshith-sb2** [comment]
I understand that I encountered a situation where Azure OpenAI changed their quota system, but the Bicep schema hasn't been updated to reflect the changes yet. In the meantime, I have been manually adjusting the quota for your deployments through the Azure OpenAI studio.

In this situation, it seems that the recommended approach is to manually reset the quota for your deployments before each deployment. You can follow these steps:

Go to the Azure OpenAI studio: Access the Azure portal and navigate to the Azure OpenAI service.

Select the Quotas tab: Find the Quotas tab or section within the Azure OpenAI service.

Adjust the TPM (Tokens Per Minute) quota: Locate the deployments you want to modify and slide the TPM value to 1K (1,000) for each of them. This will ensure that the quota aligns with your requirements.

Save or apply the changes: Once you have adjusted the TPM quota for the deployments, save or apply the changes within the Azure OpenAI studio.

By manually setting the quota in the Azure OpenAI studio, you can ensure that the deployment process aligns with the new quota system until the Bicep schema is updated to reflect the changes.

Remember to stay updated with any announcements or notifications from Azure OpenAI regarding changes to their quota system or updates to the Bicep schema in order to adjust your deployment process accordingly.

**Comment by luisquintanilla** [comment]
The plan is to have a single deployment leveraging the Turbo model. This is being tracked as part of #123

**Comment by luisquintanilla** [comment]
Text Completion Service removed as part of #162
