### ISSUE TITLE
Sharepoint Online as your knowledge base

### ISSUE THREAD

**Issue by rbakhishli1** [Azure-Samples/azure-search-openai-demo-csharp#117]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### OS and Version?
 macOS Ventura 

### Versions
>

If you would like Sharepoint online to be your knowledge base, how would you approach this challenge? Would you use a storage account and connect to Sharepoint Online using REST API https://learn.microsoft.com/en-us/azure/search/search-howto-index-sharepoint-online ? 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by luisquintanilla** [comment]
@pablocastro do you have some guidance here for ingesting data from SharePoint? Thanks!

**Comment by luisquintanilla** [comment]
Closing this issue for now since there are no immediate plans to use Sharepoint Online in this sample.

In general tough, using the latest version of the app, you could query relevant documents from Sharepoint online and add them to your prompt as context. 

https://github.com/Azure-Samples/azure-search-openai-demo-csharp/blob/64a4bcd0d7fa4c64565727cd74577b466a378e6d/app/backend/Services/ReadRetrieveReadChatService.cs#L80

For more general guidance the Retrieval Augmented Generation pattern using .NET, see [https://devblogs.microsoft.com/dotnet/demystifying-retrieval-augmented-generation-with-dotnet/](https://devblogs.microsoft.com/dotnet/demystifying-retrieval-augmented-generation-with-dotnet/)
