### ISSUE TITLE
Upload data

### ISSUE THREAD

**Issue by PhilippTP** [Azure-Samples/azure-search-openai-demo-csharp#150]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Click on "Documents" and then "Upload file"

### Any log messages given by the failure
> 

### Expected/desired behavior
> uploading files

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> 

### Mention any other details that might be useful
We implemented the solution successfully and the chatbot is working fine. But the feature "Documents", where one can upload their data, is not working. If we click "Upload Files", nothing happens. There is nothing about this topic in the readme or any other documentation. Can you help us with it?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by IEvangelist** [comment]
Hi @PhilippTP - this is a known issue; we're still working on porting some of the functionality from the original architecture over to instead using the client-side upload feature with Azure Functions and Azure Storage Blob triggers. You should see Existing documents loading though, for now this is ok - as we're still implementing the complete upload functionality.

**Comment by mosabami** [comment]
i am having the same issue and get a AuthorizationPermissionMismatch error whenever i try to upload a doc

**Comment by aaronpowell** [comment]
I've tried to replicate this issue with the latest version, but I'm unable to - the document was successfully uploaded.

Are you able to provide any more info such as:
* The region the resources are deployed to
* Full logs/stack traces of exceptions through by the application
* The document used for testing

**Comment by danielstocker** [comment]
Hi @aaronpowell and @mosabami 
I think I found the issue. 

I noticed that after doing an "azd up" on the repo the managed identity used by the API did not have the "Storage Contributor" permission.

After adding it manually and restarting the container app the uploads started working. 

![Image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/9444698/f90630a6-0e06-4301-b094-4f8d99d7fe18)


Here is the exception that I got before adding the permission - just to make sure you have the same issue:
```
Azure.RequestFailedException: This request is not authorized to perform this operation using this permission.
RequestId:a09d0bba-701e-0068-6485-0a708d000000
Time:2023-10-29T16:30:16.1590381Z
Status: 403 (This request is not authorized to perform this operation using this permission.)
ErrorCode: AuthorizationPermissionMismatch

Content:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:a09d0bba-701e-0068-6485-0a708d000000
Time:2023-10-29T16:30:16.1590381Z</Message></Error>

Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: a09d0bba-701e-0068-6485-0a708d000000
x-ms-client-request-id: 9f33ec5c-087a-463f-9f4d-eee72bfcc952
x-ms-version: 2023-08-03
x-ms-error-code: AuthorizationPermissionMismatch
Date: Sun, 29 Oct 2023 16:30:15 GMT
Content-Length: 279
Content-Type: application/xml

   at Azure.Storage.Blobs.BlockBlobRestClient.UploadAsync(Int64 contentLength, Stream body, Nullable`1 timeout, Byte[] transactionalContentMD5, String blobContentType, String blobContentEncoding, String blobContentLanguage, Byte[] blobContentMD5, String blobCacheControl, IDictionary`2 metadata, String leaseId, String blobContentDisposition, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 tier, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, String blobTagsString, Nullable`1 immutabilityPolicyExpiry, Nullable`1 immutabilityPolicyMode, Nullable`1 legalHold, Byte[] transactionalContentCrc64, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadInternal(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, IDictionary`2 tags, BlobRequestConditions conditions, Nullable`1 accessTier, BlobImmutabilityPolicy immutabilityPolicy, Nullable`1 legalHold, IProgress`1 progressHandler, UploadTransferValidationOptions transferValidationOverride, String operationName, Boolean async, CancellationToken cancellationToken)
```

I think this can be fixed by adding an additional assignment for the managed identity in the automation routine.

**Comment by aaronpowell** [comment]
Thanks @danielstocker - I'll look at adding that to the Bicep files

**Comment by PhilippTP** [comment]
@aaronpowell @danielstocker the upload works with the correct permissions. But the uploaded docs can still not be queried by the chat... the index is not updated and there are not .txt files created.

**Comment by danielstocker** [comment]
That's correct @PhilippTP - The upload code moves the selected document into blob storage and breaks it into pages. 

#160 talks about the Azure Function deployment that needs to still be added to the bicep in order to host the Embedding Function code present in the solution. It has a Storage account trigger that should fire whenever a document is dropped. The code would then complete the steps that are completed on the client side with the prepDocs.ps1/.sh script. 

I have been able to work around the limitations with the browser upload by using azd to reset the environment variable that tracks if prepdocs has been run to rebuild the index based on all files supplied locally.
