### ISSUE TITLE
GPT4

### ISSUE THREAD

**Issue by PhilippTP** [Azure-Samples/azure-search-openai-demo-csharp#172]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> change bicep and env file and set model to gpt4

### Any log messages given by the failure
> model not supported

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
Is GPT-4 not supported? We implemented the solution with gpt-4 instead of gpt 3.5 turbo. But unfortunately it is not supported (we get an error message in the thought process). Is that correct or are we missing something?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by luisquintanilla** [comment]
This sample deploys gpt3.5-turbo. Since you've already implemented a solution, I assume you already have access to GPT-4 through. To change which model gets deployed, you can change the model name in the bicep file.

https://github.com/Azure-Samples/azure-search-openai-demo-csharp/blob/b14d971be1a9305ad9c76351967138d9f132ef74/infra/main.bicep#L25

Depending on the region, which version you use and is available to you may differ. Here's the list of versions and [available regions](https://learn.microsoft.com/azure/ai-services/openai/concepts/models#gpt-4)

You can change the version here. 

https://github.com/Azure-Samples/azure-search-openai-demo-csharp/blob/b14d971be1a9305ad9c76351967138d9f132ef74/infra/main.bicep#L300

**Comment by PhilippTP** [comment]
I already changed it as you described it, but it still does not work. I got the follwoing error message:

![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/117444840/93f1969e-8a3d-41ef-b8bc-d0b27b3ab749)

**Comment by luisquintanilla** [comment]
Are you using the latest version of the app in the `main` branch? 

I believe you're seeing that error because you're using the text completions API which doesn't work with GPT-4. In recent updates to the app we removed text completions in favor of the chat completions API.

> The Chat Completion API is a new dedicated API for interacting with the GPT-35-Turbo and GPT-4 models. This API is the preferred method for accessing these models. It is also the only way to access the new GPT-4 models.

https://learn.microsoft.com/azure/ai-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions

**Comment by luisquintanilla** [comment]
Marking issue as complete. Backend and infra have been updated to allow for GPT-4 use.
