### ISSUE TITLE
Azure_OpenAI_Gpt_Deployment vs Azure_OpenAI_ChatGpt_deployment

### ISSUE THREAD

**Issue by bpw320** [Azure-Samples/azure-search-openai-demo-csharp#187]
what is the difference between Azure_OpenAI_Gpt_Deployment and Azure_OpenAI_ChatGpt_deployment?

Run azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT {Name of existing ChatGPT deployment}. Only needed if your ChatGPT deployment is not the default 'chat'.

Run azd env set AZURE_OPENAI_GPT_DEPLOYMENT {Name of existing GPT deployment}. Only needed if your ChatGPT deployment is not the default davinci.

Thanks

**Comment by luisquintanilla** [comment]
Hi @bpw320,

Thanks for your question. 

We're in the process of updating the README and will remove AZURE_OPENAI_GPT_DEPLOYMENT.

AZURE_OPENAI_CHATGPT_DEPLOYMENT is used for chat completions
AZURE_OPENAI_GPT_DEPLOYMENT was used for text completions.

In recent version of the app we've removed text completions because it's recommended to use [chat completions](https://learn.microsoft.com/azure/ai-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions). When using newer models like GPT-4, only chat completions are supported.

Hope this helps.

**Comment by bpw320** [comment]
Thanks

**Comment by bpw320** [comment]
any way to deploy this to azure without docker installed? Thanks

**Comment by luisquintanilla** [comment]
> any way to deploy this to azure without docker installed? Thanks

If you use the Codespaces / devcontainer approach, Docker is not installed in your system. 
However, because this is intended to be deployed as a containerized application, you'd need Docker. 

Alternatively, you might try the [built-in container support in the .NET SDK](https://devblogs.microsoft.com/dotnet/updates-to-container-support-in-the-dotnet-sdk/) but you'd have to update the current azd script that handles deployment.

**Comment by bpw320** [comment]
I got the following errors when running azd up:

InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is 'a5217563-2844-4d2b-b6bb-bb51da5a04a7'. See inner errors for details.

InsufficientQuota: The specified capacity '30' of account deployment is bigger than available capacity '0' for UsageName 'Tokens Per Minute (thousands) - Text-Embedding-Ada-002'.

where should I fix these issues? Thanks
